### ISSUE TITLE
Rethink the tabs layout?

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/ti-about-page#26]
![about-page](https://user-images.githubusercontent.com/3266155/58716139-09f58680-83d1-11e9-852d-30c29673db4e.png)
Now that we have more tabs, the layout of the about page is not looking that good.
One idea would be to move the tabs on the left side, on top of each other, but other ideas are welcomed 👍

**Comment by abaicus** [comment]
@rodica-andronache I have two variants that I mocked up on the run. These are just possible directions, not really tweaked. 

![image](https://user-images.githubusercontent.com/15010186/58807167-394e0280-8620-11e9-868a-3947065db434.png)


![image](https://user-images.githubusercontent.com/15010186/58807192-4965e200-8620-11e9-9511-970f8b0aff40.png)

**Comment by ineagu** [comment]
for me 1st is better because we use all screen estate vs just the middle part.

**Comment by ineagu** [comment]
free vs pro can be removed from tab list when pro is installed btw

**Comment by rodica-andronache** [comment]
yes, it's removed

**Comment by abaicus** [comment]
@selul @rodica-andronache @ineagu Here's another possible way of doing it, combining the two: 

![neve local_wp-admin_themes php_page=neve-welcome](https://user-images.githubusercontent.com/15010186/58856910-90011e00-86ac-11e9-9bf8-63ba84ac0014.png)

**Comment by abaicus** [comment]
Another iteration that encapsulates the footer in nav sidebar: 

![neve local_wp-admin_themes php_page=neve-welcome (1)](https://user-images.githubusercontent.com/15010186/58857718-91cbe100-86ae-11e9-9fec-6111c31c2002.png)

**Comment by rodica-andronache** [comment]
I love the second one

**Comment by selul** [comment]
I like more the one horizontal tabs, but the last screenshot is nice too.

**Comment by abaicus** [comment]
@selul @rodica-andronache @ineagu 
![neve local_wp-admin_themes php_page=neve-welcome (2)](https://user-images.githubusercontent.com/15010186/58868874-df077d00-86c5-11e9-8e2c-bef4680c4e1b.png)

How about something like this? I think we can also make the navigation stick to top :)

**Comment by ineagu** [comment]
For me i prefer the previous versionwith tabs on left + footer after, easier to navigate

**Comment by abaicus** [comment]
@ineagu previous version would work better for smaller screens, as we can move the sidebar after the tab on them while still having the navigation easily accessible.

**Comment by abaicus** [comment]
I meant last version*. 

That way we'd leave more space for the actual content to be displayed on smaller screens, and we'd have less scrolling if need be to navigate away from current tab. In my opinion it would be better UX wise.

**Comment by ineagu** [comment]
Sure your call
