### ISSUE TITLE
Easy Content Types conflict

### ISSUE THREAD

**Issue by SilviuDinu** [Codeinwp/ti-about-page#9]
### Description:
When activating the Easy Content Types plugin, the about page is loading a different CSS than usual and it looks weird. For example:

- Easy Content Types ACTIVE -> http://prntscr.com/m40efb
- Without Easy Content Types -> http://prntscr.com/m40epd

### How to reproduce:
1. Install and activate Easy Content Types from themeisle.com

**Comment by rodica-andronache** [comment]
@stefan-cotitosu
